lap_linter_integration
FWSCO/dbt-events-registry pull request #3
Opened 2023-12-19 15:49 UTC by lennypisano

2024-01-23 18:33 UTC, mjrsnyder requested changes

2024-01-23 18:33 UTC, mjrsnyder commented on models/dbt_event_registry_last_N_days.sql
Why was this file removed?

2024-02-02 13:11 UTC, MeravatPradeep commented on models/dbt_event_registry_last_N_days.sql
The directory got changed that is why I think it is showing the file got removed. the file is currently in the base directory.

2024-02-20 13:17 UTC, mjrsnyder approved these changes

2024-02-21 13:51 UTC, merged